name: chowbot  # Replace with your project's name
description: A new Flutter project.

# Define the environment and Dart SDK version constraints
environment:
  sdk: '>=3.5.0 <4.0.0'

# Declare the dependencies your project needs
dependencies:
  flutter:
    sdk: flutter
  serious_python: ^0.7.1  # Assuming this is a valid package
  image_picker: ^0.8.4+8
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
